services:
  go-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go_api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    restart: always
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /docs/swagger.json
    volumes:
      - ./docs:/docs

volumes:
  mongo-data:
