info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This is a sample API to demonstrate Swagger with Gin.
  title: PhotoMatch API
  version: "1.0"
paths:
  /package:
    get:
      description: Retrieve all packages from the database
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get a list of packages
      tags:
      - Package
swagger: "2.0"
