name: Go Build and Test with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' 

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Run Makefile commands
        run: make run

  docker-compose:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start services with Docker Compose
        run: docker-compose up -d --build

      - name: Run application tests inside the container
        run: docker-compose exec -T app go test -v ./...

      - name: Stop and clean up services
        run: docker-compose down