name: Go Build Check with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_FILE }}" | tr -d '\r' > .env
          echo "${{ secrets.ENV_TEST_FILE }}" | tr -d '\r' > .env.test
          printf "%s" "${{ secrets.PRIVATE_KEY }}" > private_key.json

      - name: Load Environment Variables
        run: |
          set -o allexport
          source .env
          source .env.test
          set +o allexport

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: make swag

      - name: Tidy up Go modules
        run: make tidy

      - name: Run tests
        run: make testing

  docker-compose:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build
